name: aml-Pillow
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - pandas=2.3.3
  - pip=25.2
  - pip:
      - mlflow==3.4.0
      - azureml-mlflow==1.60.0.post1
      - inference-schema[numpy-support]==1.8
      - xlrd==2.0.2
      - Pillow==11.3.0
